// このファイルは web/tools/story-swift.js が web/story.js から書き出したもの。手で直さないこと。
// 台本を直すときは story.js を直し、node web/tools/story-swift.js > このファイル で書き出し直す。

extension StoryLibrary {
    public static let scenes: [StoryScene] = [
        StoryScene(id: "prologue", kind: "prologue", chapter: nil,
                   title: "プロローグ　はじめての小児科",
                   card: StoryCard(kicker: "プロローグ", title: "はじめての小児科", sub: "ローテーション初日　朝 8 時"),
                   bg: "corridor", time: "day", end: nil, lines: [
            StoryLine(.scene, "Dum spiro, spero.　―― 息をするかぎり、希望はある。（ラテン語の格言）"),
            StoryLine(.scene, "初期研修の小児科ローテーション、初日。朝の病棟は、思っていたよりずっと静かだった。"),
            StoryLine(.scene, "廊下の突き当たりに「PICU・NICU」の自動ドア。中から、規則正しい機械の音が聞こえてくる。"),
            StoryLine(.doc, "おはようございます。今日から小児科を回る研修医の先生ですね。", mood: "happy"),
            StoryLine(.doc, "小児科と小児集中治療を担当している、いぶきです。このローテのあいだ、あなたの指導医になります。"),
            StoryLine(.doc, "まず、呼び方を決めさせてください。お名前は？", asksName: true),
            StoryLine(.doc, "{名前}先生。よろしくお願いします。", mood: "happy"),
            StoryLine(.me, "よろしくお願いします。…正直、子どもの呼吸器はまったく触ったことがなくて。"),
            StoryLine(.doc, "最初はみんなそうです。「大人の呼吸器を小さくしたもの」と思っていると、転びます。"),
            StoryLine(.scene, "いぶき先生の白衣のポケットから、白くて丸いものが、ふわりと浮かび上がった。"),
            StoryLine(.puku, "ねえねえ、この人が新しい先生？", mood: "excited"),
            StoryLine(.doc, "ぷくぷくです。ここの子たちの「息」から生まれた…ということに、なっています。", mood: "happy"),
            StoryLine(.puku, "ぼく、分からないことがあったら「なんで？」って聞く係なんだ。先生の代わりに聞いてあげる！", mood: "happy"),
            StoryLine(.puku, "じゃあさっそく。{名前}先生は、将来なに科になるの？", mood: "excited", pick: "path", choices: [
                StoryChoice(label: "小児科を考えています", reply: "それなら、この 4 週間はあなたの最初の一歩ですね。"),
                StoryChoice(label: "まだ決めていません", reply: "決めていない人ほど、よく見えるものがあります。"),
                StoryChoice(label: "ほかの科です", reply: "どの科に進んでも、子どもはいつか目の前に来ます。そのときのために。")
            ]),
            StoryLine(.puku, "ふーん。ぼく、ちゃんと覚えておくからね！", mood: "happy"),
            StoryLine(.doc, "{名前}先生、緊張していますか？", mood: "think", pick: "nerves", choices: [
                StoryChoice(label: "正直、かなり", reply: "いい緊張です。ここでは、こわいと思える人のほうが子どもを守れます。"),
                StoryChoice(label: "楽しみです", reply: "頼もしい。その気持ちのまま、手順だけは守りましょう。")
            ]),
            StoryLine(.scene, "自動ドアが開く。モニターの音、輸液ポンプの音、呼吸器の送気の音。ベッドの並ぶ PICU と、保育器の並ぶ NICU。", bg: "picu"),
            StoryLine(.doc, "ここの子たちは、体重 1 kg から 35 kg まで。呼吸を機械に預けている子もいます。"),
            StoryLine(.scene, "保育器の中で、在胎 28 週で生まれた赤ちゃんが、手のひらほどの胸を小さく上下させている。", bg: "nicu"),
            StoryLine(.puku, "ちっちゃい…。この子にも、同じ機械を使うの？", mood: "sad"),
            StoryLine(.doc, "同じ考え方で、ずっと細かく。この子に 1 回で送る空気は、小さじ 1 杯ほどです。"),
            StoryLine(.scene, "いぶき先生は保育器の前で、ほんの少しだけ長く立ち止まっていた。"),
            StoryLine(.scene, "奥のベッドには、インフルエンザ肺炎で両肺が真っ白になった 3 歳の女の子。呼吸器につながって 2 日目だ。", bg: "picu"),
            StoryLine(.scene, "隣には、RSV で入院した生後 4 か月の男の子。鼻のカニュラから高流量の酸素を受け、速い息をしている。"),
            StoryLine(.scene, "窓際の 7 歳の女の子は、ギラン・バレー症候群。呼吸の筋肉まで力が抜け、呼吸器につながって 2 週間になる。"),
            StoryLine(.doc, "覚えることは多いけれど、根っこは 1 つ。この機械が何を保証して、何をこの子に預けているか。"),
            StoryLine(.nurse, "いぶき先生、救急外来から電話です。"),
            StoryLine(.doc, "…はい。…分かりました。ベッドを空けて待っています。", mood: "think"),
            StoryLine(.doc, "8 歳の男の子。虫垂炎が破れて、お腹じゅうに膿が広がっています。血圧が保てない、ショックです。"),
            StoryLine(.doc, "昼から緊急手術。終わったら、挿管のままここへ来ます。ハルト君です。"),
            StoryLine(.puku, "手術が終わっても、チューブは抜かないの？", mood: "sad"),
            StoryLine(.doc, "ショックのあいだは、息をする仕事まで体にさせたくない。循環が落ち着くまで、呼吸は機械に預けます。"),
            StoryLine(.doc, "{名前}先生、今夜は一緒に残ってください。あなたの最初の受け持ちです。"),
            StoryLine(.puku, "いきなり!? だ、だいじょうぶかな…", mood: "alert"),
            StoryLine(.doc, "だいじょうぶ。わたしが隣にいます。まずは、機械の言葉を読めるようになりましょう。", mood: "happy")
        ]),
        StoryScene(id: "ch1-open", kind: "open", chapter: "ch1",
                   title: "第1章　扉　初日の夜",
                   card: StoryCard(kicker: "第1章", title: "機械を読む", sub: "初日の夜　PICU"),
                   bg: "night", time: "night", end: nil, lines: [
            StoryLine(.scene, "午後 8 時。手術室から、ハルト君のベッドが運ばれてきた。麻酔科医が、手際よく呼吸器につなぎ替えていく。"),
            StoryLine(.nurse, "呼吸器、つながりました。ノルアドレナリンは 0.1 で続いています。設定は麻酔科の先生が入れてくれています。"),
            StoryLine(.puku, "画面に線と数字がいっぱい…。どこから見ればいいの？", mood: "sad"),
            StoryLine(.doc, "全部を一度に見なくていい。{名前}先生、今夜は「読む」ことだけに集中しましょう。")
        ]),
        StoryScene(id: "ch1-close", kind: "close", chapter: "ch1",
                   title: "第1章　幕　午前 0 時",
                   card: nil,
                   bg: "station", time: "night", end: nil, lines: [
            StoryLine(.scene, "午前 0 時。ハルト君の数字は落ち着いている。ナースステーションには、モニターの音だけが続いている。"),
            StoryLine(.doc, "今夜、{名前}先生は 3 つ覚えました。波形の読み方。圧が 2 つあること。肺の柔らかさと、気道の通りにくさ。", mood: "happy"),
            StoryLine(.me, "読めるようにはなりました。でも、どう設定すればいいのかは、まだ…。"),
            StoryLine(.doc, "それは明日。朝の回診で、ハルト君の設定を一から見直します。"),
            StoryLine(.puku, "ねえ、息を機械で送るのって、いつからやってるの？"),
            StoryLine(.doc, "記録に残るはじまりは 1543 年。解剖学者ヴェサリウスが、動物の気管に葦の管を入れて息を吹き込みました。"),
            StoryLine(.doc, "肺がふくらむと、弱っていた心臓の動きが戻ったと書いています。人工呼吸は、1 本の管から始まったんです。"),
            StoryLine(.puku, "（あくびをして）ぷく…。明日も、ぼくついていくね。", mood: "happy")
        ]),
        StoryScene(id: "ch2-open", kind: "open", chapter: "ch2",
                   title: "第2章　扉　2 日目の朝",
                   card: StoryCard(kicker: "第2章", title: "挿管直後の初期設定", sub: "2 日目の朝　回診"),
                   bg: "picu", time: "day", end: nil, lines: [
            StoryLine(.scene, "翌朝 8 時。ハルト君の昇圧薬は、夜のうちに半分まで減った。回診の前に、夜勤の看護師から申し送りを受ける。"),
            StoryLine(.nurse, "夜中に何度か換気量のアラームが鳴って、当直の先生が一回換気量を上げていきました。"),
            StoryLine(.doc, "鳴ったから上げる。いちばん多い落とし穴です。{名前}先生、今日は設定を「決める」側に回ってもらいます。", mood: "think"),
            StoryLine(.puku, "決めるって、何から？"),
            StoryLine(.doc, "量、回数、酸素。順番に。全部、目の前の子の体重から始まります。")
        ]),
        StoryScene(id: "ch2-close", kind: "close", chapter: "ch2",
                   title: "第2章　幕　昼すぎ",
                   card: nil,
                   bg: "picu", time: "day", end: nil, lines: [
            StoryLine(.scene, "昼すぎ。ハルト君の指示票に、{名前}先生の字で書いた設定が並んでいる。"),
            StoryLine(.doc, "体重から量を、量から回数を。酸素は下げられるだけ下げる。いい初期設定です。", mood: "happy"),
            StoryLine(.me, "設定の 1 つ 1 つに、こんなに理由があるんですね。"),
            StoryLine(.puku, "ねえねえ、吸う息って英語でなんていうの？"),
            StoryLine(.doc, "インスピレーション。ラテン語の spirare、「息をする」から来ています。吐く息はエクスピレーション。"),
            StoryLine(.doc, "spirit（魂）も同じ根です。息を吹き込まれることが、昔は「ひらめき」や「命」そのものでした。"),
            StoryLine(.me, "そういえば、「いぶき」って珍しいお名前ですね。"),
            StoryLine(.doc, "息を吹く、と書いて息吹です。親がつけました。"),
            StoryLine(.puku, "ぼく、理由しってる！ あのね…", mood: "excited"),
            StoryLine(.doc, "ぷくぷく。…それは、別の機会にしましょう。", mood: "think"),
            StoryLine(.nurse, "いぶき先生、3 番ベッドのミオちゃん、また酸素化が悪くなってきています。"),
            StoryLine(.doc, "行きましょう。同じ理屈が、硬い肺ではまったく違う顔を見せます。", mood: "alert")
        ]),
        StoryScene(id: "ch3-open", kind: "open", chapter: "ch3",
                   title: "第3章　扉　3 番ベッド",
                   card: StoryCard(kicker: "第3章", title: "モードの違い", sub: "2 日目の午後　PICU 3 番ベッド"),
                   bg: "picu", time: "day", end: nil, lines: [
            StoryLine(.scene, "インフルエンザ肺炎から ARDS になったミオちゃん（3歳）。お母さんが、ベッドの横で小さな手を握っている。"),
            StoryLine(.fam, "先生、この子、ずっとこのままなんでしょうか…。", name: "ミオちゃんのお母さん"),
            StoryLine(.doc, "{名前}先生。お母さんに、いまの状態を伝えてみてください。"),
            StoryLine(.me, "（お母さんの目を見て、言葉を選ぶ）", pick: "mioMom", choices: [
                StoryChoice(label: "肺を休ませて、治るのを待っています", reply: "休ませて…。この機械は、休ませるためのものなんですね。", who: .fam, name: "ミオちゃんのお母さん"),
                StoryChoice(label: "正直、まだ分かりません", reply: "分からないことは、分からないと言っていい。ただ、いま何をしているかは伝えましょう。", who: .doc, mood: "think"),
                StoryChoice(label: "大丈夫です、きっと治ります", reply: "約束はしない。でも、希望は渡す。その間を探すのが、わたしたちの言葉です。", who: .doc, mood: "think")
            ]),
            StoryLine(.doc, "いまは肺を休ませながら、治るのを待っています。その待ち方を、いちばん安全にします。"),
            StoryLine(.puku, "待ち方？"),
            StoryLine(.doc, "機械に何を任せて、何をこの子に預けるか。それを選ぶのが「モード」です。")
        ]),
        StoryScene(id: "ch3-close", kind: "close", chapter: "ch3",
                   title: "第3章　幕　夕方",
                   card: nil,
                   bg: "picu", time: "day", end: nil, lines: [
            StoryLine(.scene, "夕方。ハルト君はうとうとしながら、自分のペースで息をしている。"),
            StoryLine(.pt, "（チューブがあって話せない。かわりに指で、小さな OK をつくってみせる）", name: "ハルト君", caseID: "postop"),
            StoryLine(.puku, "いま、ハルト君が OK って！", mood: "excited"),
            StoryLine(.doc, "自分で息をする力が戻ってきた証拠です。{名前}先生、手伝い方を選べるようになりましたね。", mood: "happy"),
            StoryLine(.me, "自分のペースの息、ですね。"),
            StoryLine(.doc, "「息」という字は、「自」と「心」。「自」は、もとは鼻をかたどった字だといわれます。"),
            StoryLine(.doc, "鼻と、胸の奥の心。休息の「息」でもあります。ハルト君の息も、少し休めるようになりました。"),
            StoryLine(.puku, "じゃあ、もうチューブ抜けるね！", mood: "excited"),
            StoryLine(.doc, "まだです。昇圧薬が少し残っていて、お腹も張っています。明日の朝の数字を見てから決めましょう。"),
            StoryLine(.doc, "明日は、機械の外から答え合わせをします。血液ガスです。")
        ]),
        StoryScene(id: "ch4-open", kind: "open", chapter: "ch4",
                   title: "第4章　扉　3 日目の朝",
                   card: StoryCard(kicker: "第4章", title: "血液ガスを読む", sub: "3 日目の朝　回診前"),
                   bg: "station", time: "day", end: nil, lines: [
            StoryLine(.scene, "3 日目の朝。回診の前に、ナースステーションに夜のあいだの採血の結果が並んでいる。"),
            StoryLine(.me, "数字が多すぎて、どれから見ればいいのか…。"),
            StoryLine(.doc, "呼吸器の画面は「送ったもの」。血液ガスは「体に届いたもの」。両方を見て、はじめて答え合わせになります。"),
            StoryLine(.puku, "体に届いた酸素は、そのあとどうなるの？"),
            StoryLine(.doc, "燃えます、ゆっくりと。18 世紀にラボアジエが、呼吸は炭が燃えるのと同じ燃焼だと示しました。"),
            StoryLine(.doc, "酸素を使って、二酸化炭素を出す。「酸素」という日本語は、江戸の蘭学者・宇田川榕菴の訳語です。"),
            StoryLine(.puku, "答え合わせ、ぼく得意！ …たぶん。", mood: "happy")
        ]),
        StoryScene(id: "ch4-close", kind: "close", chapter: "ch4",
                   title: "第4章　幕　夕方",
                   card: nil,
                   bg: "picu", time: "day", end: nil, lines: [
            StoryLine(.scene, "夕方。ミオちゃんの pH は低めのまま。それでも、肺にかかる圧は上限の下に収まった。"),
            StoryLine(.me, "CO₂ が高いままでいいのか、まだ少し怖いです。"),
            StoryLine(.doc, "その怖さは大事にしてください。許すのは、肺を守るという目的があるときだけです。"),
            StoryLine(.fam, "先生たち、今日は何度も見に来てくださったんですね。", name: "ミオちゃんのお母さん"),
            StoryLine(.doc, "今夜はわたしの当直です。{名前}先生も一緒に。鳴ってからの動き方を体に入れます。", mood: "think")
        ]),
        StoryScene(id: "ch5-open", kind: "open", chapter: "ch5",
                   title: "第5章　扉　2 回目の当直",
                   card: StoryCard(kicker: "第5章", title: "アラームとトラブル", sub: "3 日目の夜　当直"),
                   bg: "station", time: "night", end: nil, lines: [
            StoryLine(.scene, "2 回目の当直。ナースステーションで、ななみさんが {名前}先生に声をかけた。"),
            StoryLine(.nurse, "ハルト君、夕方に点滴の管が詰まって、左の鎖骨の下から入れ直しています。昇圧薬は、もう切れました。"),
            StoryLine(.nurse, "今夜は静かだといいですね。…って言うと、たいてい鳴るんですけど。"),
            StoryLine(.puku, "ぼく、アラームが鳴ると頭が真っ白になっちゃうんだ。", mood: "sad"),
            StoryLine(.doc, "だから順番を決めておきます。頭が真っ白になっても、手が先に動くように。")
        ]),
        StoryScene(id: "ch5-close", kind: "close", chapter: "ch5",
                   title: "第5章　幕　夜明け",
                   card: nil,
                   bg: "dawn", time: "day", end: nil, lines: [
            StoryLine(.scene, "夜明け。ハルト君の胸には細いドレーンが入り、モニターの音はまた高く澄んだ音に戻っている。"),
            StoryLine(.me, "手が震えていました。でも、酸素を上げるところまでは、考える前にできました。"),
            StoryLine(.doc, "それで十分です。今夜ハルト君を守ったのは、{名前}先生の最初の一手です。", mood: "happy"),
            StoryLine(.doc, "夕方の管の針が、肺の表面をかすめたのかもしれません。そこから、機械の圧で空気が漏れました。", mood: "think"),
            StoryLine(.puku, "気胸って、英語だとなんていうの？"),
            StoryLine(.doc, "ニューモソラックス。ギリシャ語のプネウマ「息・風・霊」に、胸を意味するソラックスです。"),
            StoryLine(.doc, "古代の医師は、体をめぐる生命の息をプネウマと呼びました。肺炎のニューモニアも同じ仲間の言葉です。"),
            StoryLine(.puku, "ぼく、ずっとポケットの中で震えてた…。", mood: "sad"),
            StoryLine(.doc, "知っています。わたしの最初の当直の夜も、そうでしたね。", mood: "happy"),
            StoryLine(.me, "…先生の、最初の当直の夜も？"),
            StoryLine(.scene, "いぶき先生は答えずに、白んでいく窓の外を見ていた。"),
            StoryLine(.doc, "ここから先は、外す話です。つけるより、外すほうが難しい。")
        ]),
        StoryScene(id: "ch6-open", kind: "open", chapter: "ch6",
                   title: "第6章　扉　4 日目の朝",
                   card: StoryCard(kicker: "第6章", title: "離脱と抜管", sub: "4 日目の朝　PICU"),
                   bg: "picu", time: "day", end: nil, lines: [
            StoryLine(.scene, "翌朝。ハルト君の熱は下がり、お腹の張りも引いた。ドレーンからの空気漏れも止まっている。お母さんが面会に来ている。"),
            StoryLine(.fam, "先生、この管はいつ抜けるんでしょう。あの子、しゃべりたがっていて。", name: "ハルト君のお母さん"),
            StoryLine(.doc, "今日から、それを確かめていきます。{名前}先生、条件を一緒に見ましょう。"),
            StoryLine(.puku, "抜けたら、ハルト君とおしゃべりできる？", mood: "excited"),
            StoryLine(.doc, "できます。そのためにも、焦らないことです。", mood: "happy")
        ]),
        StoryScene(id: "ch6-close", kind: "close", chapter: "ch6",
                   title: "第6章　幕　抜管のあと",
                   card: nil,
                   bg: "picu", time: "day", bgm: "breath", end: nil, lines: [
            StoryLine(.scene, "抜管から 1 時間。ハルト君は酸素マスクをつけて、自分でしっかり咳をしている。"),
            StoryLine(.pt, "…せんせい。のど、いたい。", name: "ハルト君"),
            StoryLine(.puku, "しゃべった！", mood: "excited"),
            StoryLine(.fam, "ハルト…！ 先生、ほんとうにありがとうございました。", name: "ハルト君のお母さん"),
            StoryLine(.doc, "お礼は、こちらの先生に。最初の夜から、ずっとハルト君の担当でした。", mood: "happy"),
            StoryLine(.me, "ハルト君、よくがんばったね。"),
            StoryLine(.pt, "…せんせいの、なまえ、なに？", name: "ハルト君", caseID: "postop"),
            StoryLine(.me, "{名前}。{名前}先生だよ。"),
            StoryLine(.pt, "…{名前}せんせい。ねてるとき、ずっと、こえ、きこえてた。", name: "ハルト君", caseID: "postop"),
            StoryLine(.puku, "チューブが入っていたときは、どうして声が出なかったの？"),
            StoryLine(.doc, "声は、吐く息が声帯を震わせて出るものです。チューブは、その声帯のあいだを通っていました。"),
            StoryLine(.doc, "だから最初の声は、自分の息が戻ってきた合図なんです。", mood: "happy"),
            StoryLine(.doc, "チューブが抜けた日のことを、子どもは覚えていません。でも、親は一生覚えています。", mood: "think"),
            StoryLine(.scene, "そう言ういぶき先生は、ハルト君ではなく、どこか遠くを見ているようだった。")
        ]),
        StoryScene(id: "ch7-open", kind: "open", chapter: "ch7",
                   title: "第7章　扉　5 日目の朝",
                   card: StoryCard(kicker: "第7章", title: "細い気道", sub: "5 日目の朝　PICU 5 番ベッド"),
                   bg: "picu", time: "day", end: nil, lines: [
            StoryLine(.scene, "ハルト君が抜管された翌朝。空いたベッドに、朝の光が差している。"),
            StoryLine(.nurse, "{名前}先生、5 番ベッドのそうた君、夜のあいだに呼吸回数を 40 まで上げています。"),
            StoryLine(.doc, "そうた君は、今日から{名前}先生の受け持ちです。挿管した夜のこと、覚えていますか。", mood: "think"),
            StoryLine(.me, "はい。吐ききれずに、血圧が下がって…。"),
            StoryLine(.puku, "また回数が上がってる！", mood: "alert"),
            StoryLine(.doc, "あの夜と同じ落とし穴です。今度は、{名前}先生が組み直してください。")
        ]),
        StoryScene(id: "ch7-close", kind: "close", chapter: "ch7",
                   title: "第7章　幕　8 日目の昼前",
                   card: nil,
                   bg: "picu", time: "day", bgm: "breath", end: nil, lines: [
            StoryLine(.scene, "8 日目の昼前。そうた君は鼻のカニュラで、ゆっくりと息をしている。"),
            StoryLine(.scene, "お母さんが差し出した指を、小さな手がぎゅっと握った。"),
            StoryLine(.fam, "先生、この子、握り返してくれました…！", name: "そうた君のお母さん"),
            StoryLine(.puku, "「息子」って、どうして「息」の字なの？"),
            StoryLine(.doc, "「息」には、生まれる、ふえるという意味もあります。利息の「息」も同じです。"),
            StoryLine(.doc, "むすこの「むす」は、苔むすの「むす」。息をして、育っていく子です。", mood: "happy"),
            StoryLine(.doc, "回数より量、吐かせて待つ。{名前}先生の設定で、そうた君は乗りきりました。", mood: "happy"),
            StoryLine(.puku, "ぼく、吐く時間のこと、もう忘れないよ。", mood: "happy"),
            StoryLine(.doc, "ミオちゃんの回診に行きましょう。あの子も、良くなってきています。")
        ]),
        StoryScene(id: "ch8-open", kind: "open", chapter: "ch8",
                   title: "第8章　扉　3 番ベッド、ふたたび",
                   card: StoryCard(kicker: "第8章", title: "硬い肺をもう一度", sub: "8 日目の昼　PICU 3 番ベッド"),
                   bg: "picu", time: "day", end: nil, lines: [
            StoryLine(.scene, "3 番ベッドのミオちゃんは、呼吸器につながって 9 日目。酸素の量が減り、熱も下がりはじめた。"),
            StoryLine(.fam, "先生、昨日より顔色がいいって、看護師さんが。", name: "ミオちゃんのお母さん"),
            StoryLine(.fam, "「休ませて、治るのを待っている」と聞いてから、待つのが少し楽になりました。", name: "ミオちゃんのお母さん", when: "mioMom:0"),
            StoryLine(.fam, "「まだ分からない」と正直に言ってもらえたから、いまの「良くなっている」を信じられます。", name: "ミオちゃんのお母さん", when: "mioMom:1"),
            StoryLine(.fam, "「きっと治る」と言ってもらえた日から、ずっとそれを支えにしていました。", name: "ミオちゃんのお母さん", when: "mioMom:2"),
            StoryLine(.doc, "はい。肺が少しずつ戻ってきています。ここからは、良くなるほうの話をしましょう。", mood: "happy"),
            StoryLine(.nurse, "では、床ずれ予防の体位変換をしますね。{名前}先生、チューブを見ていてください。"),
            StoryLine(.puku, "ぼくも見張ってる！", mood: "excited")
        ]),
        StoryScene(id: "ch8-close", kind: "close", chapter: "ch8",
                   title: "第8章　幕　12 日目の夕方",
                   card: nil,
                   bg: "picu", time: "day", bgm: "memory", end: nil, lines: [
            StoryLine(.scene, "12 日目の夕方。ミオちゃんは HFNC をつけたまま、お母さんの膝で絵本を見ている。"),
            StoryLine(.fam, "チューブが抜けた日は、心臓が止まるかと思いました。", name: "ミオちゃんのお母さん"),
            StoryLine(.doc, "わたしもです。でも、{名前}先生が設定を一から組み直してくれました。"),
            StoryLine(.puku, "いぶき先生のお母さんも、前にそう言ってたよね。"),
            StoryLine(.doc, "ぷくぷく。", mood: "think"),
            StoryLine(.puku, "…ぷく。（ポケットにもぐる）", mood: "sad"),
            StoryLine(.me, "あの日、先生がバッグを押していた数分は、すごく長く感じました。"),
            StoryLine(.doc, "1952 年のコペンハーゲンでは、ポリオの子たちのために、医学生が交代で何週間もバッグを押し続けました。"),
            StoryLine(.doc, "千人を超える学生の手が、多くの命をつないだ。集中治療室は、そこから始まったといわれます。"),
            StoryLine(.me, "量、PEEP、酸素、回数。順番を覚えていたから、手が動きました。"),
            StoryLine(.doc, "それが「覚えた」ということです。明日から、{名前}先生は NICU に入ります。", mood: "happy"),
            StoryLine(.puku, "NICU って、あのちっちゃい子たちのところ？", mood: "excited")
        ]),
        StoryScene(id: "ch9-open", kind: "open", chapter: "ch9",
                   title: "第9章　扉　NICU の夜",
                   card: StoryCard(kicker: "第9章", title: "手のひらの肺", sub: "2 週目の夜　NICU"),
                   bg: "nicu", time: "night", bgm: "nicu", end: nil, lines: [
            StoryLine(.scene, "2 週目。NICU の夜は、PICU よりさらに静かだ。保育器のファンの音だけが続いている。"),
            StoryLine(.nurse, "{名前}先生、産科から連絡です。在胎 28 週、もうすぐ生まれます。"),
            StoryLine(.doc, "ローテの初日に見た、保育器の子と同じ週数です。分娩室へ行きましょう。"),
            StoryLine(.puku, "28 週って、本当なら、まだお母さんのお腹の中にいる時期だよね…", mood: "sad"),
            StoryLine(.doc, "あと 3 か月、お腹の中で肺を育てるはずだった子です。その続きを、外で手伝います。"),
            StoryLine(.doc, "この週数では、肺胞をしぼませない物質、サーファクタントがまだ足りません。"),
            StoryLine(.doc, "人工のサーファクタントで赤ちゃんを初めて救ったのは、1980 年、日本の藤原哲郎先生たちです。"),
            StoryLine(.scene, "いぶき先生の声は、いつもより少しだけ硬かった。")
        ]),
        StoryScene(id: "ch9-close", kind: "close", chapter: "ch9",
                   title: "第9章　幕　生まれて 4 日目",
                   card: nil,
                   bg: "nicu", time: "day", bgm: "nicu", end: nil, lines: [
            StoryLine(.scene, "生まれて 4 日目。あおい君は nCPAP のまま、保育器の中で手足を伸ばしている。"),
            StoryLine(.fam, "小さすぎて、触ったら壊れてしまいそうで…。", name: "あおい君のお父さん"),
            StoryLine(.doc, "{名前}先生、お父さんに声をかけてあげてください。"),
            StoryLine(.me, "（保育器の窓を、お父さんと一緒にのぞきこむ）", pick: "aoiDad", choices: [
                StoryChoice(label: "一緒に、手を当ててみましょう", reply: "…あったかい。こんなに小さいのに、ちゃんと息をしてる。", who: .fam, name: "あおい君のお父さん"),
                StoryChoice(label: "もう少し大きくなってから", reply: "触れることも治療のうちです。いまのふれあいは、親にも子にも力になります。", who: .doc, mood: "think")
            ]),
            StoryLine(.nurse, "大丈夫ですよ。手のひらで、そっと包んであげてください。", when: "aoiDad:1"),
            StoryLine(.doc, "桁が変わっても、考え方は同じでした。{名前}先生、もう NICU の数字も読めますね。", mood: "happy"),
            StoryLine(.me, "小さじ 1 杯の空気が、こんなに重いとは思いませんでした。"),
            StoryLine(.puku, "あおい君、生まれたとき泣いた？"),
            StoryLine(.doc, "小さな声で。産声は、水で満ちていた肺に初めて空気を入れて、それを吐きながら上げる声です。"),
            StoryLine(.scene, "保育器の向こうの壁に、NICU を巣立った子どもたちの写真が並んでいる。", bgm: "memory"),
            StoryLine(.scene, "端の色あせた 1 枚に、手書きの文字。「いぶきちゃん　在胎 28 週　980 g」"),
            StoryLine(.me, "（色あせた写真から、目が離せない）", pick: "photo", choices: [
                StoryChoice(label: "先生、これって…", reply: "あ…見つかっちゃった。", who: .puku, mood: "alert"),
                StoryChoice(label: "（何も言わずに、先生を見る）", reply: "…{名前}先生、気づいちゃった？", who: .puku, mood: "sad")
            ]),
            StoryLine(.doc, "わたしも、ここの保育器で育ちました。小さじ 1 杯の空気から。", mood: "happy"),
            StoryLine(.doc, "続きは、別の機会にしましょう。いまは、あおい君の番です。")
        ]),
        StoryScene(id: "ch10-open", kind: "open", chapter: "ch10",
                   title: "第10章　扉　救急外来からの電話",
                   card: StoryCard(kicker: "第10章", title: "吐けない息", sub: "3 週目の夕方　救急外来"),
                   bg: "station", time: "night", end: nil, lines: [
            StoryLine(.scene, "3 週目、PICU に戻って最初の当直。夕方、救急外来から電話が鳴った。"),
            StoryLine(.nurse, "11 歳の男の子、喘息の発作です。吸入が効かなくて、いま挿管しています！"),
            StoryLine(.doc, "{名前}先生、行きましょう。喘息の子の呼吸器は、ほかのどの子とも違います。", mood: "alert"),
            StoryLine(.puku, "違うって、どこが？", mood: "alert"),
            StoryLine(.doc, "吸わせることより、吐かせることがすべて。今夜は、それだけ覚えてください。"),
            StoryLine(.doc, "「呼吸」という言葉も、「呼」が吐く、「吸」が吸う。吐くほうが先に書いてあります。"),
            StoryLine(.puku, "ほんとだ！ 吐かないと、吸えないんだね。", mood: "excited")
        ]),
        StoryScene(id: "ch10-close", kind: "close", chapter: "ch10",
                   title: "第10章　幕　病棟へ移る日",
                   card: nil,
                   bg: "picu", time: "day", end: nil, lines: [
            StoryLine(.scene, "抜管の翌日。レン君は一般病棟へ移る前に、吸入器の使い方をもう一度教わっている。"),
            StoryLine(.pt, "…ちゃんと毎日やります。あんなに苦しいのは、もう嫌だ。", name: "レン君", caseID: "asthma"),
            StoryLine(.doc, "吸入ステロイドは、発作のない日のための薬です。続けた日の分だけ、発作が遠くなります。"),
            StoryLine(.me, "呼吸器を外すまでが治療じゃないんですね。"),
            StoryLine(.doc, "そうです。次の発作を起こさないところまでが、わたしたちの仕事です。", mood: "happy"),
            StoryLine(.doc, "喘息の英語アズマは、ギリシャ語の「あえぎ」。2000 年以上前の医師も、この苦しさを書き残しています。"),
            StoryLine(.doc, "{名前}先生。初日の夜は、画面の線と数字を前に、手が止まっていましたね。"),
            StoryLine(.doc, "あの夜は、吐ききれているかを真っ先に見ていた。わたしが言う前に。", mood: "happy"),
            StoryLine(.puku, "ぼくが「なんで？」って聞く前に、もう答えてたよ！", mood: "excited")
        ]),
        StoryScene(id: "ch11-open", kind: "open", chapter: "ch11",
                   title: "第11章　扉　窓際のベッド",
                   card: StoryCard(kicker: "第11章", title: "力を取り戻す", sub: "3 週目　PICU 窓際のベッド"),
                   bg: "picu", time: "day", end: nil, lines: [
            StoryLine(.scene, "窓際のベッドのあかりちゃん。挿管から 4 週間。初日より、指先がよく動くようになった。"),
            StoryLine(.pt, "（文字盤を指でたどる。「いつ、しゃべれる？」）", name: "あかりちゃん", caseID: "gbs"),
            StoryLine(.me, "（あかりちゃんの目の高さまで、しゃがむ）", pick: "akari", choices: [
                StoryChoice(label: "もうすぐ。一緒に練習しよう", reply: "（文字盤をたどる。「やくそく」）", who: .pt, name: "あかりちゃん", caseID: "gbs"),
                StoryChoice(label: "息の力が戻ったらね", reply: "（小さくうなずいて、文字盤をたどる。「がんばる」）", who: .pt, name: "あかりちゃん", caseID: "gbs")
            ]),
            StoryLine(.puku, "この前の SBT、18 分でだめだったんだよね…", mood: "sad"),
            StoryLine(.doc, "あの日から、毎日少しずつ練習してきました。{名前}先生、仕上げを一緒にやりましょう。"),
            StoryLine(.puku, "息の筋肉が動かない病気って、昔はどうしてたの？"),
            StoryLine(.doc, "1928 年、ボストンで「鉄の肺」が作られました。体ごと箱に入れ、外から胸を広げて息をさせる機械です。"),
            StoryLine(.doc, "ポリオの子たちが、その中で何か月も力が戻るのを待ちました。あかりちゃんも、いま待っています。"),
            StoryLine(.me, "あかりちゃん、仕上げだよ。")
        ]),
        StoryScene(id: "ch11-close", kind: "close", chapter: "ch11",
                   title: "第11章　幕　4 週間ぶりの声",
                   card: nil,
                   bg: "picu", time: "day", bgm: "breath", end: nil, lines: [
            StoryLine(.scene, "抜管の翌日。あかりちゃんは NPPV のマスクを外して、窓の外を見ている。"),
            StoryLine(.pt, "…{名前}せんせい。こえ、でた。", name: "あかりちゃん", caseID: "gbs"),
            StoryLine(.pt, "…やくそく、まもったよ。", name: "あかりちゃん", caseID: "gbs", when: "akari:0"),
            StoryLine(.puku, "しゃべった！ 4 週間ぶりだよ！", mood: "excited"),
            StoryLine(.fam, "先生方、本当に、本当にありがとうございました。", name: "あかりちゃんのお母さん"),
            StoryLine(.doc, "{名前}先生。ローテが終わるまで、あと 1 週間です。", mood: "happy")
        ]),
        StoryScene(id: "epilogue", kind: "epilogue", chapter: nil,
                   title: "エピローグ　ローテーション最終日",
                   card: StoryCard(kicker: "エピローグ", title: "ローテーション最終日", sub: "夕方　PICU"),
                   bg: "dawn", time: "day", bgm: "epilogue", end: StoryEnd(label: "症例で練習する", action: "cases", say: "おつかれさまでした。6 人の子どもたちを、今度はひとりで受け持ってみましょう。"), lines: [
            StoryLine(.scene, "4 週間のローテーション、最終日。夕方の PICU で、また新しい入院の電話が鳴っている。"),
            StoryLine(.scene, "ベッドの顔ぶれは入れ替わった。ミオちゃんは一般病棟へ移り、そうた君はとうに家へ帰った。"),
            StoryLine(.scene, "あかりちゃんはリハビリで車いすに乗れるようになり、レン君は吸入を続けると約束して退院した。"),
            StoryLine(.scene, "NICU のあおい君は 1,400 g を超えた。退院したハルト君からは、手紙が届いている。"),
            StoryLine(.scene, "封筒には、大きな字で「{名前}せんせいへ」。"),
            StoryLine(.pt, "「ぼくがねてるとき、ずっとそばにいてくれて、ありがとう。またサッカーできたよ。」", name: "ハルト君（手紙）", caseID: "postop"),
            StoryLine(.doc, "{名前}先生。初日に、子どもの呼吸器は触ったことがないと言っていましたね。"),
            StoryLine(.me, "…はい。いまも、全部分かったとは思えません。"),
            StoryLine(.doc, "それでいいんです。分からないと思える人は、確かめに戻ってこられます。", mood: "happy"),
            StoryLine(.doc, "初日、とても緊張していると言っていましたね。その緊張が、ずっと子どもたちを守っていました。", when: "nerves:0"),
            StoryLine(.doc, "初日、楽しみだと言っていましたね。その顔のまま、最後まで来ました。", when: "nerves:1"),
            StoryLine(.me, "先生。NICU の写真の続き、聞いてもいいですか。", bgm: "memory"),
            StoryLine(.doc, "約束でしたね。", mood: "happy", when: "photo:0"),
            StoryLine(.doc, "あの写真の前で、何も聞かずにいてくれましたね。…お話しします。", mood: "happy", when: "photo:1"),
            StoryLine(.doc, "わたしは 28 週、980 g で生まれて、2 週間、呼吸器につながっていました。"),
            StoryLine(.doc, "管が抜けて、初めて自分で息をした日。両親は、この名前に決めたそうです。息吹。"),
            StoryLine(.puku, "そのとき、ぼくが生まれたんだ！ 先生の、はじめての息から。", mood: "excited"),
            StoryLine(.doc, "…ということに、なっています。研修医としてここへ戻った日、ポケットから出てきました。"),
            StoryLine(.doc, "「息を引き取る」という言葉があります。始まりが息なら、終わりも息で言い表すんです。", mood: "think"),
            StoryLine(.doc, "そのあいだを少しでも長く、楽にする。それが、わたしたちの仕事です。"),
            StoryLine(.puku, "ねえ{名前}先生。初日に聞いたこと、覚えてる？ なに科になるの？", bgm: "epilogue"),
            StoryLine(.me, "…やっぱり、小児科です。ここに戻ってきたいです。", when: "path:0"),
            StoryLine(.doc, "待っています。わたしも、そうやってここへ戻ってきましたから。", mood: "happy", when: "path:0"),
            StoryLine(.me, "まだ決めていません。でも、子どもの息の音は、たぶん一生忘れません。", when: "path:1"),
            StoryLine(.doc, "それで十分です。どの科にも、息をする子どもは来ます。", mood: "happy", when: "path:1"),
            StoryLine(.me, "進む科は変わりません。でも、子どもが来たら、逃げずに診ます。", when: "path:2"),
            StoryLine(.doc, "それが聞けたら、このローテは成功です。", mood: "happy", when: "path:2"),
            StoryLine(.puku, "{名前}先生、ぼくのこと、忘れないでね。", mood: "sad"),
            StoryLine(.doc, "忘れませんよ。呼吸器の前に立つたびに、「なんで？」と聞く声がするはずです。", mood: "happy"),
            StoryLine(.puku, "…ねえ、{名前}先生のポケット、ちょっとあったかそう。", mood: "happy"),
            StoryLine(.doc, "ふふ。そうかもしれませんね。", mood: "happy"),
            StoryLine(.doc, "最後に、ひとりで受け持ってみてください。症例は 6 人。わたしは、呼ばれたら行きます。"),
            StoryLine(.scene, "ベッドの横で、まだ誰にもつながっていない呼吸器が、起動を待っている。"),
            StoryLine(.doc, "人形や物語に命を与えることを、「息を吹き込む」と言いますね。", mood: "think"),
            StoryLine(.doc, "この機械がするのも、同じことです。吹き込むのは、{名前}先生の手です。", mood: "happy"),
            StoryLine(.scene, "{名前}先生は、起動スイッチに指をかけた。")
        ])
    ]

    /// 研修手帳（web/story.js の NOTEBOOK）。
    public static let notebook: [StoryNote] = [
        StoryNote(id: "secret-1",
                  kind: .secret,
                  scene: "prologue",
                  hint: "ローテ初日の朝",
                  title: "息から生まれた",
                  text: "ぷくぷくは、ここの子たちの「息」から生まれた…ということに、なっているらしい。いぶき先生は、28 週の赤ちゃんの保育器の前で、少しだけ長く立ち止まっていた。"),
        StoryNote(id: "secret-2",
                  kind: .secret,
                  scene: "ch2-close",
                  hint: "2 日目の昼すぎ",
                  title: "息吹という名前",
                  text: "先生の名前は、息を吹くと書いて「息吹」。ご両親がつけたそうだ。理由を言いかけたぷくぷくを、先生は止めた。"),
        StoryNote(id: "secret-3",
                  kind: .secret,
                  scene: "ch5-close",
                  hint: "2 回目の当直の明け方",
                  title: "最初の当直の夜",
                  text: "先生が研修医だったころの最初の当直の夜も、ぷくぷくはポケットで震えていたらしい。ぷくぷくは、そんなに前から先生と一緒にいる。"),
        StoryNote(id: "secret-4",
                  kind: .secret,
                  scene: "ch6-close",
                  hint: "ハルト君が抜管した日",
                  title: "親は一生覚えている",
                  text: "「チューブが抜けた日のことを、子どもは覚えていません。でも、親は一生覚えています」。そう言った先生は、どこか遠くを見ていた。"),
        StoryNote(id: "secret-5",
                  kind: .secret,
                  scene: "ch8-close",
                  hint: "ミオちゃんの 12 日目",
                  title: "先生のお母さん",
                  text: "ぷくぷくは、いぶき先生のお母さんを知っているようだ。「前にそう言ってた」。先生は名前を呼んだだけで、その先を言わせなかった。"),
        StoryNote(id: "secret-6",
                  kind: .secret,
                  scene: "ch9-close",
                  hint: "NICU の 2 週目",
                  title: "色あせた写真",
                  text: "NICU を巣立った子どもたちの写真の端に、「いぶきちゃん　在胎 28 週　980 g」。先生も、ここの保育器で育った。"),
        StoryNote(id: "secret-7",
                  kind: .secret,
                  scene: "epilogue",
                  hint: "ローテ最終日",
                  title: "はじめての息",
                  text: "先生は 2 週間呼吸器につながり、初めて自分で息をした日に「息吹」と名づけられた。ぷくぷくはその息から生まれた…と、先生は思っている。研修医としてここへ戻った日、ポケットから出てきたそうだ。"),
        StoryNote(id: "lore-reed",
                  kind: .lore,
                  scene: "ch1-close",
                  hint: "初日の夜",
                  title: "葦の管",
                  text: "1543 年、解剖学者ヴェサリウスは『人体の構造について（ファブリカ）』に、動物の気管に葦の管を入れて息を吹き込み、肺をふくらませ続ける方法を書いた。記録に残る人工呼吸のはじまりの 1 つとされる。",
                  source: "A. Vesalius『De humani corporis fabrica』1543 年"),
        StoryNote(id: "lore-spirit",
                  kind: .lore,
                  scene: "ch2-close",
                  hint: "2 日目の昼すぎ",
                  title: "spirit と inspiration",
                  text: "吸気 inspiration と呼気 expiration は、ラテン語 spirare（息をする）から。spirit（霊・精神）、inspiration（ひらめき＝息を吹き込まれること）、expire（息を吐ききる→命が尽きる、期限が切れる）、respiration（呼吸）も同じ根を持つ。",
                  source: "英語の語源辞典（Online Etymology Dictionary など）"),
        StoryNote(id: "lore-kanji",
                  kind: .lore,
                  scene: "ch3-close",
                  hint: "2 日目の夕方",
                  title: "「息」という字",
                  text: "「息」は「自」と「心」でできている。後漢の字書『説文解字』は「自」を鼻と説く。休息・安息のように、「やすむ」という意味も持つ。",
                  source: "許慎『説文解字』"),
        StoryNote(id: "lore-fire",
                  kind: .lore,
                  scene: "ch4-open",
                  hint: "3 日目の朝",
                  title: "呼吸はゆっくりした燃焼",
                  text: "18 世紀の終わり、ラボアジエはラプラスとともに、呼吸は炭が燃えるのと同じく酸素を使って二酸化炭素を出す、ゆっくりした燃焼だと示した。「酸素」という日本語は、蘭学者・宇田川榕菴が『舎密開宗』で用いた訳語。",
                  source: "Lavoisier & Laplace「熱についての論考」1783 年／宇田川榕菴『舎密開宗』"),
        StoryNote(id: "lore-pneuma",
                  kind: .lore,
                  scene: "ch5-close",
                  hint: "2 回目の当直の明け方",
                  title: "プネウマ",
                  text: "ギリシャ語 pneuma は「息・風・霊」。気胸 pneumothorax は pneuma と胸 thorax から。肺炎 pneumonia は肺 pneumon からで、同じ「息をする」の語に連なる。古代ギリシャ・ローマの医学は、体をめぐる生命の息をプネウマと呼んだ。",
                  source: "医学用語の語源（ギリシャ語）"),
        StoryNote(id: "lore-voice",
                  kind: .lore,
                  scene: "ch6-close",
                  hint: "ハルト君が抜管した日",
                  title: "声は吐く息",
                  text: "声は、吐く息が声帯を震わせて生まれる。挿管中はチューブが声帯のあいだを通るので、声が出ない。抜管のあとの最初の声は、自分の息が戻ってきた合図。",
                  source: "発声の生理"),
        StoryNote(id: "lore-musuko",
                  kind: .lore,
                  scene: "ch7-close",
                  hint: "そうた君の 8 日目",
                  title: "息子",
                  text: "「息」には、生まれる・ふえるという意味もある（子息、利息）。「むすこ」の「むす」は「苔むす」の「むす」と同じで、生まれる・生じるという意味。",
                  source: "国語辞典・漢和辞典"),
        StoryNote(id: "lore-copenhagen",
                  kind: .lore,
                  scene: "ch8-close",
                  hint: "ミオちゃんの 12 日目",
                  title: "コペンハーゲン 1952",
                  text: "1952 年、コペンハーゲンでポリオが大流行した。麻酔科医イプセンの提案で、気管切開と手で押す陽圧換気が行われ、千人を超える医学生が交代でバッグを押し続けた。死亡率は大きく下がり、集中治療室のはじまりとされる。",
                  source: "B. Ibsen ほか、1952 年コペンハーゲンのポリオ流行の記録"),
        StoryNote(id: "lore-surfactant",
                  kind: .lore,
                  scene: "ch9-open",
                  hint: "NICU の 2 週目",
                  title: "藤原哲郎とサーファクタント",
                  text: "1980 年、岩手医科大学の藤原哲郎らは、人工サーファクタントで早産児の呼吸窮迫症候群（RDS）を治療した成果を Lancet に報告した。この治療は、のちに世界の標準になった。",
                  source: "Fujiwara T, et al. Lancet 1980;1:55–59"),
        StoryNote(id: "lore-ubugoe",
                  kind: .lore,
                  scene: "ch9-close",
                  hint: "あおい君の 4 日目",
                  title: "産声",
                  text: "生まれる前の肺は、水で満たされている。生まれてすぐの大きな息で肺に空気が入り、その息を吐きながら上げるのが産声。",
                  source: "新生児の呼吸の生理"),
        StoryNote(id: "lore-kokyu",
                  kind: .lore,
                  scene: "ch10-open",
                  hint: "3 週目の当直",
                  title: "呼が先",
                  text: "「呼吸」の「呼」は吐く、「吸」は吸う。呼気・吸気も同じ並び。吐ききらなければ、次の息は入らない。",
                  source: "漢和辞典"),
        StoryNote(id: "lore-asthma",
                  kind: .lore,
                  scene: "ch10-close",
                  hint: "レン君が病棟へ移る日",
                  title: "アズマ",
                  text: "喘息 asthma は、ギリシャ語の asthma（あえぎ・息切れ）から。ヒポクラテス派の医学書にも、すでにこの言葉が出てくる。",
                  source: "医学用語の語源（ギリシャ語）"),
        StoryNote(id: "lore-ironlung",
                  kind: .lore,
                  scene: "ch11-open",
                  hint: "あかりちゃんの 4 週目",
                  title: "鉄の肺",
                  text: "1928 年、ボストンのドリンカーとショウは、首から下を密閉した箱に入れ、箱の中の圧を下げて胸を広げる「鉄の肺」を実用化した。ポリオで呼吸の筋肉がまひした多くの子どもが、その中で回復を待った。",
                  source: "Drinker P, Shaw LA. J Clin Invest 1929;7:229–247"),
        StoryNote(id: "lore-hikitoru",
                  kind: .lore,
                  scene: "epilogue",
                  hint: "ローテ最終日",
                  title: "息を引き取る",
                  text: "亡くなることを「息を引き取る」という。最期の息を体に引き入れて、それきり終わる、という見方がよく知られる（語源には諸説ある）。人の始まりも終わりも、息で言い表されてきた。",
                  source: "国語辞典（語源は諸説）"),
        StoryNote(id: "growth-ch1",
                  kind: .growth,
                  scene: "ch1-close",
                  hint: "初日の夜",
                  title: "呼吸器の画面を読む",
                  before: "線と数字が並ぶ画面の、どこから見ればいいか分からなかった。",
                  now: "3 本の波形、PIP と Pplat、肺の硬さ（コンプライアンス）と気道の通りにくさ（抵抗）を読める。"),
        StoryNote(id: "growth-ch2",
                  kind: .growth,
                  scene: "ch2-close",
                  hint: "2 日目の昼すぎ",
                  title: "初期設定を決める",
                  before: "設定は「誰かが入れてくれたもの」だった。",
                  now: "体重から一回換気量を、そこから回数を決め、PEEP と FiO₂ で酸素化を合わせられる。"),
        StoryNote(id: "growth-ch3",
                  kind: .growth,
                  scene: "ch3-close",
                  hint: "2 日目の夕方",
                  title: "モードを選ぶ",
                  before: "量で決めるか圧で決めるか、何が違うのか分からなかった。",
                  now: "量か圧か、トリガ、SIMV と PSV。機械に任せることと、子どもに預けることを選べる。"),
        StoryNote(id: "growth-ch4",
                  kind: .growth,
                  scene: "ch4-close",
                  hint: "3 日目の夕方",
                  title: "血液ガスで答え合わせ",
                  before: "並んだ数字の、どれから見ればいいか分からなかった。",
                  now: "4 つの手順で読み、CO₂ は換気量で、酸素化は PEEP と FiO₂ で動かせる。CO₂ を許す理由も言える。"),
        StoryNote(id: "growth-ch5",
                  kind: .growth,
                  scene: "ch5-close",
                  hint: "2 回目の当直の明け方",
                  title: "アラームに順番で動く",
                  before: "アラームが鳴ると、頭が真っ白になった。",
                  now: "圧の上昇、吐ききれない息、SpO₂ の低下を、決めた順番で切り分けられる。"),
        StoryNote(id: "growth-ch6",
                  kind: .growth,
                  scene: "ch6-close",
                  hint: "ハルト君が抜管した日",
                  title: "外す",
                  before: "「つける」ことしか考えていなかった。",
                  now: "離脱の条件を確かめ、SBT で見極め、抜管したあとを見守れる。"),
        StoryNote(id: "growth-ch7",
                  kind: .growth,
                  scene: "ch7-close",
                  hint: "そうた君の 8 日目",
                  title: "細い気道の乳児を受け持つ",
                  before: "回数を上げれば CO₂ は下がる、と思っていた。",
                  now: "吐ける回数で組み、痰づまりに手を打ち、高流量鼻カニュラへつなげられる。"),
        StoryNote(id: "growth-ch8",
                  kind: .growth,
                  scene: "ch8-close",
                  hint: "ミオちゃんの 12 日目",
                  title: "一から組み直す",
                  before: "チューブが抜けたら、何から始めればいいか分からなかった。",
                  now: "量、PEEP、酸素、回数の順に組み直し、良くなるにつれて酸素と PEEP を下げていける。"),
        StoryNote(id: "growth-ch9",
                  kind: .growth,
                  scene: "ch9-close",
                  hint: "あおい君の 4 日目",
                  title: "手のひらの肺",
                  before: "小さじ 1 杯の空気の世界は、見学するだけだった。",
                  now: "1 kg の子の初期設定を決め、サーファクタントのあとに合わせ、CPAP へ抜管できる。"),
        StoryNote(id: "growth-ch10",
                  kind: .growth,
                  scene: "ch10-close",
                  hint: "レン君が病棟へ移る日",
                  title: "吐かせる換気",
                  before: "息は「吸わせるもの」だと思っていた。",
                  now: "吐ききれているかを先に見て、回数を落とし、CO₂ を許しながら血圧を守れる。"),
        StoryNote(id: "growth-ch11",
                  kind: .growth,
                  scene: "ch11-close",
                  hint: "あかりちゃんの 4 週目",
                  title: "休ませながら鍛える",
                  before: "一度だめだった SBT は、失敗だと思っていた。",
                  now: "弱った呼吸の筋肉を休ませながら鍛え、3 回目の SBT で抜管へつなげられる。")
    ]
}
